# CircleCI Config 2017 test
version: 2

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:6.10.3

jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      # restore npm module dependencies from cache
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      # setup npm
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      # publish npm
      - deploy:
        name: publish-npm
        command: npm publish --access public
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test-unit:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: mkdir -p ./test/results
      - run: npm -s run test:xunit > ./test/results/tape.xml
      - store_artifacts:
          path: ./test/results/
          prefix: test
      - store_test_results:
          path: ./test/results/
  test-coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: mkdir -p ./test/results
      - run: npm -s run test:coverage-check
      - store_artifacts:
          path: coverage
          prefix: test
      - store_test_results:
          path: coverage
  # test-coverage:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run: npm -s run test:coverage-check
  #     - store_artifacts:
  #         path: coverage
  #         prefix: test
  #     - store_test_results:
  #         path: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup:
          filters:
              branches:
                ignore: 
                  - /feature*/
                  - /bugfix*/
      - test-unit:
          requires:
            - setup
          filters:
            branches:
              ignore: 
                - /feature*/
                - /bugfix*/             
      - test-coverage:
          requires:
            - setup
          filters:
            branches:
              ignore: 
                - /feature*/
                - /bugfix*/
      # - build:
      #   requires:
      #     - setup
      #     - test-unit
      #     - test-coverage
      #   filters:
      #       tags:
      #         only: /v[0-9]+(\.[0-9]+)*/
      #       branches:
      #         only: 
      #           - master
      #           - develop
